// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Wbn.GestaoAdm.Infrastructure.Persistence.Contexts;

#nullable disable

namespace Wbn.GestaoAdm.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260414224221_InitialCreate_Schema")]
    partial class InitialCreate_Schema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Wbn.GestaoAdm.Domain.Modules.Cfg.Entities.CfgConsulta", b =>
                {
                    b.Property<string>("Identificador")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("identificador");

                    b.Property<string>("BuscaDescricao")
                        .HasColumnType("varchar(150)")
                        .HasColumnName("buscaDescricao");

                    b.Property<string>("BuscaIdentificador")
                        .HasColumnType("varchar(150)")
                        .HasColumnName("buscaIdentificador");

                    b.Property<string>("BuscarCodigoAlternativo")
                        .HasColumnType("varchar(150)")
                        .HasColumnName("buscarCodigoAlternativo");

                    b.Property<string>("CampoChavePrimaria")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("campoChavePrimaria");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("descricao");

                    b.Property<string>("Observacao")
                        .HasColumnType("text")
                        .HasColumnName("observacao");

                    b.Property<string>("Sql")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sql");

                    b.HasKey("Identificador");

                    b.ToTable("cfgWeb", (string)null);

                    b.HasData(
                        new
                        {
                            Identificador = "conferenciaFila",
                            BuscaDescricao = "empresaNome",
                            BuscaIdentificador = "codigoRecebimento",
                            BuscarCodigoAlternativo = "id",
                            CampoChavePrimaria = "r.id",
                            Descricao = "Fila de conferência",
                            Observacao = "Fila operacional da conferência de recebimentos.",
                            Sql = "SELECT r.id, r.codigoRecebimento, r.statusRecebimento, e.nomeFantasia AS empresaNome, u.nome AS usuarioEnvioNome, r.origem, r.dataEnvio, r.dataAtualizacao FROM recebimentos r INNER JOIN empresas e ON e.id = r.empresaId INNER JOIN usuarios u ON u.id = r.usuarioEnvioId WHERE r.statusRecebimento IN (1, 2) ${WHEREOUT} ${ORDERBY}"
                        });
                });

            modelBuilder.Entity("Wbn.GestaoAdm.Domain.Modules.Cfg.Entities.SubCfgCampo", b =>
                {
                    b.Property<string>("Identificador")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("identificador");

                    b.Property<string>("Campo")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("campo");

                    b.Property<string>("CampoBusca")
                        .IsRequired()
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("campoBusca");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("descricao");

                    b.Property<string>("IdentificadorCfg")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasColumnName("identificadorCfg");

                    b.Property<int>("LarguraColuna")
                        .HasColumnType("int")
                        .HasColumnName("larguraColuna");

                    b.Property<string>("Mascara")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("mascara");

                    b.Property<int>("OrdemCampo")
                        .HasColumnType("int")
                        .HasColumnName("ordemCampo");

                    b.Property<bool>("PermitirFiltro")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("permitirFiltro");

                    b.Property<string>("TipoDados")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("tipoDados");

                    b.Property<bool>("Visivel")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("visivel");

                    b.HasKey("Identificador");

                    b.HasIndex("IdentificadorCfg");

                    b.ToTable("subCFGWeb", (string)null);

                    b.HasData(
                        new
                        {
                            Identificador = "conferenciaFila_id",
                            Campo = "id",
                            CampoBusca = "r.id",
                            Descricao = "Id",
                            IdentificadorCfg = "conferenciaFila",
                            LarguraColuna = 80,
                            OrdemCampo = 0,
                            PermitirFiltro = true,
                            TipoDados = "integer",
                            Visivel = true
                        },
                        new
                        {
                            Identificador = "conferenciaFila_codigoRecebimento",
                            Campo = "codigoRecebimento",
                            CampoBusca = "r.codigoRecebimento",
                            Descricao = "Código",
                            IdentificadorCfg = "conferenciaFila",
                            LarguraColuna = 180,
                            OrdemCampo = 1,
                            PermitirFiltro = true,
                            TipoDados = "string",
                            Visivel = true
                        },
                        new
                        {
                            Identificador = "conferenciaFila_statusRecebimento",
                            Campo = "statusRecebimento",
                            CampoBusca = "r.statusRecebimento",
                            Descricao = "Status",
                            IdentificadorCfg = "conferenciaFila",
                            LarguraColuna = 120,
                            OrdemCampo = 2,
                            PermitirFiltro = true,
                            TipoDados = "integer",
                            Visivel = true
                        },
                        new
                        {
                            Identificador = "conferenciaFila_empresaNome",
                            Campo = "empresaNome",
                            CampoBusca = "e.nomeFantasia",
                            Descricao = "Empresa",
                            IdentificadorCfg = "conferenciaFila",
                            LarguraColuna = 220,
                            OrdemCampo = 3,
                            PermitirFiltro = true,
                            TipoDados = "string",
                            Visivel = true
                        },
                        new
                        {
                            Identificador = "conferenciaFila_usuarioEnvioNome",
                            Campo = "usuarioEnvioNome",
                            CampoBusca = "u.nome",
                            Descricao = "Usuário envio",
                            IdentificadorCfg = "conferenciaFila",
                            LarguraColuna = 220,
                            OrdemCampo = 4,
                            PermitirFiltro = true,
                            TipoDados = "string",
                            Visivel = true
                        },
                        new
                        {
                            Identificador = "conferenciaFila_origem",
                            Campo = "origem",
                            CampoBusca = "r.origem",
                            Descricao = "Origem",
                            IdentificadorCfg = "conferenciaFila",
                            LarguraColuna = 120,
                            OrdemCampo = 5,
                            PermitirFiltro = true,
                            TipoDados = "string",
                            Visivel = true
                        },
                        new
                        {
                            Identificador = "conferenciaFila_dataEnvio",
                            Campo = "dataEnvio",
                            CampoBusca = "r.dataEnvio",
                            Descricao = "Data envio",
                            IdentificadorCfg = "conferenciaFila",
                            LarguraColuna = 160,
                            OrdemCampo = 6,
                            PermitirFiltro = true,
                            TipoDados = "dateTime",
                            Visivel = true
                        },
                        new
                        {
                            Identificador = "conferenciaFila_dataAtualizacao",
                            Campo = "dataAtualizacao",
                            CampoBusca = "r.dataAtualizacao",
                            Descricao = "Data atualização",
                            IdentificadorCfg = "conferenciaFila",
                            LarguraColuna = 160,
                            OrdemCampo = 7,
                            PermitirFiltro = true,
                            TipoDados = "dateTime",
                            Visivel = true
                        });
                });

            modelBuilder.Entity("Wbn.GestaoAdm.Domain.Modules.Empresas.Entities.Empresa", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("varchar(14)")
                        .HasColumnName("cnpj");

                    b.Property<string>("CodigoInterno")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("codigoInterno");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime")
                        .HasColumnName("dataAtualizacao");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime")
                        .HasColumnName("dataCadastro");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("email");

                    b.Property<string>("NomeFantasia")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("nomeFantasia");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("razaoSocial");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("telefone");

                    b.HasKey("Id");

                    b.HasIndex("Cnpj")
                        .IsUnique();

                    b.HasIndex("CodigoInterno")
                        .IsUnique();

                    b.ToTable("empresas", (string)null);
                });

            modelBuilder.Entity("Wbn.GestaoAdm.Domain.Modules.Perfis.Entities.Perfil", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime")
                        .HasColumnName("dataAtualizacao");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime")
                        .HasColumnName("dataCadastro");

                    b.Property<string>("Descricao")
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("perfis", (string)null);
                });

            modelBuilder.Entity("Wbn.GestaoAdm.Domain.Modules.Recebimentos.Entities.Arquivo", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<string>("CaminhoArquivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("caminhoArquivo");

                    b.Property<DateTime>("DataUpload")
                        .HasColumnType("datetime")
                        .HasColumnName("dataUpload");

                    b.Property<string>("Extensao")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("extensao");

                    b.Property<string>("MimeType")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("mimeType");

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nomeArquivo");

                    b.Property<string>("NomeOriginal")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nomeOriginal");

                    b.Property<int>("OrdemExibicao")
                        .HasColumnType("int")
                        .HasColumnName("ordemExibicao");

                    b.Property<ulong>("RecebimentoId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("recebimentoId");

                    b.Property<long>("TamanhoBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("tamanhoBytes");

                    b.Property<ulong>("TipoDocumentoId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("tipoDocumentoId");

                    b.HasKey("Id");

                    b.HasIndex("RecebimentoId");

                    b.HasIndex("TipoDocumentoId");

                    b.ToTable("arquivos", (string)null);
                });

            modelBuilder.Entity("Wbn.GestaoAdm.Domain.Modules.Recebimentos.Entities.Boleto", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<ulong?>("ArquivoId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("arquivoId");

                    b.Property<string>("Beneficiario")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("beneficiario");

                    b.Property<string>("CodigoBarras")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("codigoBarras");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime")
                        .HasColumnName("dataAtualizacao");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime")
                        .HasColumnName("dataCadastro");

                    b.Property<DateTime?>("DataEmissao")
                        .HasColumnType("date")
                        .HasColumnName("dataEmissao");

                    b.Property<DateTime?>("DataVencimento")
                        .HasColumnType("date")
                        .HasColumnName("dataVencimento");

                    b.Property<string>("DocumentoBeneficiario")
                        .HasMaxLength(18)
                        .HasColumnType("varchar(18)")
                        .HasColumnName("documentoBeneficiario");

                    b.Property<string>("LinhaDigitavel")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("linhaDigitavel");

                    b.Property<string>("Observacao")
                        .HasColumnType("text")
                        .HasColumnName("observacao");

                    b.Property<ulong>("RecebimentoId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("recebimentoId");

                    b.Property<decimal>("ValorBoleto")
                        .HasPrecision(15, 2)
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("valorBoleto");

                    b.HasKey("Id");

                    b.HasIndex("ArquivoId")
                        .IsUnique();

                    b.HasIndex("LinhaDigitavel");

                    b.HasIndex("RecebimentoId");

                    b.ToTable("boletos", (string)null);
                });

            modelBuilder.Entity("Wbn.GestaoAdm.Domain.Modules.Recebimentos.Entities.NotaFiscal", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<ulong?>("ArquivoId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("arquivoId");

                    b.Property<string>("ChaveAcesso")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("chaveAcesso");

                    b.Property<string>("CpfCnpjEmitente")
                        .HasMaxLength(18)
                        .HasColumnType("varchar(18)")
                        .HasColumnName("cpfCnpjEmitente");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime")
                        .HasColumnName("dataAtualizacao");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime")
                        .HasColumnName("dataCadastro");

                    b.Property<DateTime?>("DataEmissao")
                        .HasColumnType("date")
                        .HasColumnName("dataEmissao");

                    b.Property<DateTime?>("DataEntrada")
                        .HasColumnType("date")
                        .HasColumnName("dataEntrada");

                    b.Property<string>("NomeEmitente")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("nomeEmitente");

                    b.Property<string>("NumeroNota")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("numeroNota");

                    b.Property<string>("Observacao")
                        .HasColumnType("text")
                        .HasColumnName("observacao");

                    b.Property<ulong>("RecebimentoId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("recebimentoId");

                    b.Property<string>("Serie")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("serie");

                    b.Property<decimal>("ValorTotal")
                        .HasPrecision(15, 2)
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("valorTotal");

                    b.HasKey("Id");

                    b.HasIndex("ArquivoId")
                        .IsUnique();

                    b.HasIndex("ChaveAcesso")
                        .IsUnique();

                    b.HasIndex("RecebimentoId");

                    b.ToTable("notasFiscais", (string)null);
                });

            modelBuilder.Entity("Wbn.GestaoAdm.Domain.Modules.Recebimentos.Entities.NotaFiscalBoleto", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<ulong>("BoletoId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("boletoId");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime")
                        .HasColumnName("dataCadastro");

                    b.Property<ulong>("NotaFiscalId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("notaFiscalId");

                    b.HasKey("Id");

                    b.HasIndex("BoletoId");

                    b.HasIndex("NotaFiscalId", "BoletoId")
                        .IsUnique();

                    b.ToTable("notaFiscalBoleto", (string)null);
                });

            modelBuilder.Entity("Wbn.GestaoAdm.Domain.Modules.Recebimentos.Entities.Recebimento", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<string>("CodigoRecebimento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("codigoRecebimento");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("datetime")
                        .HasColumnName("dataAtualizacao");

                    b.Property<DateTime>("DataEnvio")
                        .HasColumnType("datetime")
                        .HasColumnName("dataEnvio");

                    b.Property<DateTime>("DataRecebimento")
                        .HasColumnType("datetime")
                        .HasColumnName("dataRecebimento");

                    b.Property<ulong>("EmpresaId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("empresaId");

                    b.Property<string>("Observacao")
                        .HasColumnType("text")
                        .HasColumnName("observacao");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("origem");

                    b.Property<int>("StatusRecebimento")
                        .HasColumnType("int")
                        .HasColumnName("statusRecebimento");

                    b.Property<ulong>("UsuarioEnvioId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("usuarioEnvioId");

                    b.HasKey("Id");

                    b.HasIndex("CodigoRecebimento")
                        .IsUnique();

                    b.HasIndex("EmpresaId");

                    b.HasIndex("UsuarioEnvioId");

                    b.ToTable("recebimentos", (string)null);
                });

            modelBuilder.Entity("Wbn.GestaoAdm.Domain.Modules.Recebimentos.Entities.RecebimentoComentario", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<string>("Comentario")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("comentario");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime")
                        .HasColumnName("dataAtualizacao");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime")
                        .HasColumnName("dataCadastro");

                    b.Property<ulong>("RecebimentoId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("recebimentoId");

                    b.Property<ulong>("UsuarioId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("usuarioId");

                    b.Property<bool>("VisivelParaEmpresa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("visivelParaEmpresa");

                    b.HasKey("Id");

                    b.HasIndex("RecebimentoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("recebimentoComentarios", (string)null);
                });

            modelBuilder.Entity("Wbn.GestaoAdm.Domain.Modules.Recebimentos.Entities.RecebimentoConferencia", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<bool>("BoletoEncontrado")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("boletoEncontrado");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime")
                        .HasColumnName("dataCadastro");

                    b.Property<DateTime>("DataConferencia")
                        .HasColumnType("datetime")
                        .HasColumnName("dataConferencia");

                    b.Property<bool>("DataVencimentoConfere")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("dataVencimentoConfere");

                    b.Property<bool>("DocumentoConfere")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("documentoConfere");

                    b.Property<bool>("NotaEncontrada")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("notaEncontrada");

                    b.Property<string>("Observacao")
                        .HasColumnType("text")
                        .HasColumnName("observacao");

                    b.Property<ulong>("RecebimentoId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("recebimentoId");

                    b.Property<string>("StatusConferencia")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("statusConferencia");

                    b.Property<ulong>("UsuarioConferenciaId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("usuarioConferenciaId");

                    b.Property<bool>("ValorConfere")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("valorConfere");

                    b.HasKey("Id");

                    b.HasIndex("RecebimentoId");

                    b.HasIndex("UsuarioConferenciaId");

                    b.ToTable("recebimentoConferencias", (string)null);
                });

            modelBuilder.Entity("Wbn.GestaoAdm.Domain.Modules.Recebimentos.Entities.RecebimentoDivergencia", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime")
                        .HasColumnName("dataAtualizacao");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime")
                        .HasColumnName("dataCadastro");

                    b.Property<DateTime?>("DataResolucao")
                        .HasColumnType("datetime")
                        .HasColumnName("dataResolucao");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<string>("ObservacaoResolucao")
                        .HasColumnType("text")
                        .HasColumnName("observacaoResolucao");

                    b.Property<ulong>("RecebimentoId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("recebimentoId");

                    b.Property<bool>("Resolvida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("resolvida");

                    b.Property<int>("StatusDivergencia")
                        .HasColumnType("int")
                        .HasColumnName("statusDivergencia");

                    b.Property<string>("TipoDivergencia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("tipoDivergencia");

                    b.Property<ulong>("UsuarioId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("usuarioId");

                    b.Property<ulong?>("UsuarioResolucaoId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("usuarioResolucaoId");

                    b.HasKey("Id");

                    b.HasIndex("RecebimentoId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("UsuarioResolucaoId");

                    b.ToTable("recebimentoDivergencias", (string)null);
                });

            modelBuilder.Entity("Wbn.GestaoAdm.Domain.Modules.Recebimentos.Entities.RecebimentoHistorico", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("acao");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime")
                        .HasColumnName("dataCadastro");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<ulong>("RecebimentoId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("recebimentoId");

                    b.Property<ulong?>("UsuarioId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("usuarioId");

                    b.HasKey("Id");

                    b.HasIndex("RecebimentoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("recebimentoHistoricos", (string)null);
                });

            modelBuilder.Entity("Wbn.GestaoAdm.Domain.Modules.TiposDocumento.Entities.TipoDocumento", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime")
                        .HasColumnName("dataCadastro");

                    b.Property<string>("Descricao")
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("tiposDocumento", (string)null);
                });

            modelBuilder.Entity("Wbn.GestaoAdm.Domain.Modules.Usuarios.Entities.Usuario", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime")
                        .HasColumnName("dataAtualizacao");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime")
                        .HasColumnName("dataCadastro");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("email");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("login");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("nome");

                    b.Property<ulong>("PerfilId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("perfilId");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("senhaHash");

                    b.Property<sbyte>("StatusSenha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((sbyte)0)
                        .HasColumnName("statusSenha");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("telefone");

                    b.Property<DateTime?>("UltimoLogin")
                        .HasColumnType("datetime")
                        .HasColumnName("ultimoLogin");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Login")
                        .IsUnique();

                    b.HasIndex("PerfilId");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("Wbn.GestaoAdm.Domain.Modules.UsuariosEmpresas.Entities.UsuarioEmpresa", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime")
                        .HasColumnName("dataCadastro");

                    b.Property<ulong>("EmpresaId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("empresaId");

                    b.Property<ulong>("UsuarioId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("usuarioId");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("UsuarioId", "EmpresaId")
                        .IsUnique();

                    b.ToTable("usuarioEmpresa", (string)null);
                });

            modelBuilder.Entity("Wbn.GestaoAdm.Domain.Modules.Cfg.Entities.SubCfgCampo", b =>
                {
                    b.HasOne("Wbn.GestaoAdm.Domain.Modules.Cfg.Entities.CfgConsulta", "CfgConsulta")
                        .WithMany("SubCfgCampos")
                        .HasForeignKey("IdentificadorCfg")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CfgConsulta");
                });

            modelBuilder.Entity("Wbn.GestaoAdm.Domain.Modules.Recebimentos.Entities.Arquivo", b =>
                {
                    b.HasOne("Wbn.GestaoAdm.Domain.Modules.Recebimentos.Entities.Recebimento", "Recebimento")
                        .WithMany("Arquivos")
                        .HasForeignKey("RecebimentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wbn.GestaoAdm.Domain.Modules.TiposDocumento.Entities.TipoDocumento", "TipoDocumento")
                        .WithMany("Arquivos")
                        .HasForeignKey("TipoDocumentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Recebimento");

                    b.Navigation("TipoDocumento");
                });

            modelBuilder.Entity("Wbn.GestaoAdm.Domain.Modules.Recebimentos.Entities.Boleto", b =>
                {
                    b.HasOne("Wbn.GestaoAdm.Domain.Modules.Recebimentos.Entities.Arquivo", "Arquivo")
                        .WithOne("Boleto")
                        .HasForeignKey("Wbn.GestaoAdm.Domain.Modules.Recebimentos.Entities.Boleto", "ArquivoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Wbn.GestaoAdm.Domain.Modules.Recebimentos.Entities.Recebimento", "Recebimento")
                        .WithMany("Boletos")
                        .HasForeignKey("RecebimentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Arquivo");

                    b.Navigation("Recebimento");
                });

            modelBuilder.Entity("Wbn.GestaoAdm.Domain.Modules.Recebimentos.Entities.NotaFiscal", b =>
                {
                    b.HasOne("Wbn.GestaoAdm.Domain.Modules.Recebimentos.Entities.Arquivo", "Arquivo")
                        .WithOne("NotaFiscal")
                        .HasForeignKey("Wbn.GestaoAdm.Domain.Modules.Recebimentos.Entities.NotaFiscal", "ArquivoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Wbn.GestaoAdm.Domain.Modules.Recebimentos.Entities.Recebimento", "Recebimento")
                        .WithMany("NotasFiscais")
                        .HasForeignKey("RecebimentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Arquivo");

                    b.Navigation("Recebimento");
                });

            modelBuilder.Entity("Wbn.GestaoAdm.Domain.Modules.Recebimentos.Entities.NotaFiscalBoleto", b =>
                {
                    b.HasOne("Wbn.GestaoAdm.Domain.Modules.Recebimentos.Entities.Boleto", "Boleto")
                        .WithMany("NotasFiscaisBoletos")
                        .HasForeignKey("BoletoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wbn.GestaoAdm.Domain.Modules.Recebimentos.Entities.NotaFiscal", "NotaFiscal")
                        .WithMany("NotasFiscaisBoletos")
                        .HasForeignKey("NotaFiscalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Boleto");

                    b.Navigation("NotaFiscal");
                });

            modelBuilder.Entity("Wbn.GestaoAdm.Domain.Modules.Recebimentos.Entities.Recebimento", b =>
                {
                    b.HasOne("Wbn.GestaoAdm.Domain.Modules.Empresas.Entities.Empresa", "Empresa")
                        .WithMany("Recebimentos")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Wbn.GestaoAdm.Domain.Modules.Usuarios.Entities.Usuario", "UsuarioEnvio")
                        .WithMany("RecebimentosEnviados")
                        .HasForeignKey("UsuarioEnvioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empresa");

                    b.Navigation("UsuarioEnvio");
                });

            modelBuilder.Entity("Wbn.GestaoAdm.Domain.Modules.Recebimentos.Entities.RecebimentoComentario", b =>
                {
                    b.HasOne("Wbn.GestaoAdm.Domain.Modules.Recebimentos.Entities.Recebimento", "Recebimento")
                        .WithMany("Comentarios")
                        .HasForeignKey("RecebimentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wbn.GestaoAdm.Domain.Modules.Usuarios.Entities.Usuario", "Usuario")
                        .WithMany("Comentarios")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Recebimento");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Wbn.GestaoAdm.Domain.Modules.Recebimentos.Entities.RecebimentoConferencia", b =>
                {
                    b.HasOne("Wbn.GestaoAdm.Domain.Modules.Recebimentos.Entities.Recebimento", "Recebimento")
                        .WithMany("Conferencias")
                        .HasForeignKey("RecebimentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wbn.GestaoAdm.Domain.Modules.Usuarios.Entities.Usuario", "UsuarioConferencia")
                        .WithMany("Conferencias")
                        .HasForeignKey("UsuarioConferenciaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Recebimento");

                    b.Navigation("UsuarioConferencia");
                });

            modelBuilder.Entity("Wbn.GestaoAdm.Domain.Modules.Recebimentos.Entities.RecebimentoDivergencia", b =>
                {
                    b.HasOne("Wbn.GestaoAdm.Domain.Modules.Recebimentos.Entities.Recebimento", "Recebimento")
                        .WithMany("Divergencias")
                        .HasForeignKey("RecebimentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wbn.GestaoAdm.Domain.Modules.Usuarios.Entities.Usuario", "Usuario")
                        .WithMany("DivergenciasRegistradas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Wbn.GestaoAdm.Domain.Modules.Usuarios.Entities.Usuario", "UsuarioResolucao")
                        .WithMany("DivergenciasResolvidas")
                        .HasForeignKey("UsuarioResolucaoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Recebimento");

                    b.Navigation("Usuario");

                    b.Navigation("UsuarioResolucao");
                });

            modelBuilder.Entity("Wbn.GestaoAdm.Domain.Modules.Recebimentos.Entities.RecebimentoHistorico", b =>
                {
                    b.HasOne("Wbn.GestaoAdm.Domain.Modules.Recebimentos.Entities.Recebimento", "Recebimento")
                        .WithMany("Historicos")
                        .HasForeignKey("RecebimentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wbn.GestaoAdm.Domain.Modules.Usuarios.Entities.Usuario", "Usuario")
                        .WithMany("Historicos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Recebimento");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Wbn.GestaoAdm.Domain.Modules.Usuarios.Entities.Usuario", b =>
                {
                    b.HasOne("Wbn.GestaoAdm.Domain.Modules.Perfis.Entities.Perfil", "Perfil")
                        .WithMany("Usuarios")
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("Wbn.GestaoAdm.Domain.Modules.UsuariosEmpresas.Entities.UsuarioEmpresa", b =>
                {
                    b.HasOne("Wbn.GestaoAdm.Domain.Modules.Empresas.Entities.Empresa", "Empresa")
                        .WithMany("UsuariosEmpresas")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wbn.GestaoAdm.Domain.Modules.Usuarios.Entities.Usuario", "Usuario")
                        .WithMany("UsuariosEmpresas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Wbn.GestaoAdm.Domain.Modules.Cfg.Entities.CfgConsulta", b =>
                {
                    b.Navigation("SubCfgCampos");
                });

            modelBuilder.Entity("Wbn.GestaoAdm.Domain.Modules.Empresas.Entities.Empresa", b =>
                {
                    b.Navigation("Recebimentos");

                    b.Navigation("UsuariosEmpresas");
                });

            modelBuilder.Entity("Wbn.GestaoAdm.Domain.Modules.Perfis.Entities.Perfil", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Wbn.GestaoAdm.Domain.Modules.Recebimentos.Entities.Arquivo", b =>
                {
                    b.Navigation("Boleto");

                    b.Navigation("NotaFiscal");
                });

            modelBuilder.Entity("Wbn.GestaoAdm.Domain.Modules.Recebimentos.Entities.Boleto", b =>
                {
                    b.Navigation("NotasFiscaisBoletos");
                });

            modelBuilder.Entity("Wbn.GestaoAdm.Domain.Modules.Recebimentos.Entities.NotaFiscal", b =>
                {
                    b.Navigation("NotasFiscaisBoletos");
                });

            modelBuilder.Entity("Wbn.GestaoAdm.Domain.Modules.Recebimentos.Entities.Recebimento", b =>
                {
                    b.Navigation("Arquivos");

                    b.Navigation("Boletos");

                    b.Navigation("Comentarios");

                    b.Navigation("Conferencias");

                    b.Navigation("Divergencias");

                    b.Navigation("Historicos");

                    b.Navigation("NotasFiscais");
                });

            modelBuilder.Entity("Wbn.GestaoAdm.Domain.Modules.TiposDocumento.Entities.TipoDocumento", b =>
                {
                    b.Navigation("Arquivos");
                });

            modelBuilder.Entity("Wbn.GestaoAdm.Domain.Modules.Usuarios.Entities.Usuario", b =>
                {
                    b.Navigation("Comentarios");

                    b.Navigation("Conferencias");

                    b.Navigation("DivergenciasRegistradas");

                    b.Navigation("DivergenciasResolvidas");

                    b.Navigation("Historicos");

                    b.Navigation("RecebimentosEnviados");

                    b.Navigation("UsuariosEmpresas");
                });
#pragma warning restore 612, 618
        }
    }
}
