CREATE TABLE IF NOT EXISTS `nfeDocumentos` (
    `id`                     BIGINT UNSIGNED  NOT NULL AUTO_INCREMENT,
    `empresaId`              BIGINT UNSIGNED  NOT NULL,
    `chaveAcesso`            VARCHAR(44)      NOT NULL,
    `nsu`                    BIGINT           NULL,
    `tipoDocumento`          VARCHAR(50)      NULL,
    `schemaDocumento`        VARCHAR(100)     NULL,
    `cnpjEmitente`           VARCHAR(14)      NULL,
    `nomeEmitente`           VARCHAR(255)     NULL,
    `cnpjDestinatario`       VARCHAR(14)      NULL,
    `nomeDestinatario`       VARCHAR(255)     NULL,
    `numeroNota`             VARCHAR(20)      NULL,
    `serie`                  VARCHAR(10)      NULL,
    `dataEmissao`            DATETIME         NULL,
    `valorTotal`             DECIMAL(15,2)    NULL,
    `statusManifestacao`     VARCHAR(50)      NULL,
    `xmlResumo`              LONGTEXT         NULL,
    `xmlCompleto`            LONGTEXT         NULL,
    `xmlEvento`              LONGTEXT         NULL,
    `protocoloManifestacao`  VARCHAR(100)     NULL,
    `retornoSefaz`           LONGTEXT         NULL,
    `dataDownload`           DATETIME         NULL,
    `dataCriacao`            DATETIME         NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `dataAtualizacao`        DATETIME         NULL,
    CONSTRAINT `pk_nfeDocumentos`             PRIMARY KEY (`id`),
    CONSTRAINT `uk_nfeDocumentos_chaveAcesso` UNIQUE (`chaveAcesso`),
    CONSTRAINT `fk_nfeDocumentos_empresas`    FOREIGN KEY (`empresaId`) REFERENCES `empresas` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `nfeProdutos` (
    `id`              BIGINT UNSIGNED  NOT NULL AUTO_INCREMENT,
    `nfeDocumentoId`  BIGINT UNSIGNED  NOT NULL,
    `codigoProduto`   VARCHAR(100)     NULL,
    `nomeProduto`     VARCHAR(500)     NOT NULL,
    `descricao`       VARCHAR(1000)    NULL,
    `ncm`             VARCHAR(20)      NULL,
    `cfop`            VARCHAR(10)      NULL,
    `unidade`         VARCHAR(20)      NULL,
    `quantidade`      DECIMAL(15,4)    NULL,
    `valorUnitario`   DECIMAL(15,4)    NULL,
    `valorTotal`      DECIMAL(15,2)    NULL,
    `ean`             VARCHAR(50)      NULL,
    `dataCriacao`     DATETIME         NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `dataAtualizacao` DATETIME         NULL,
    CONSTRAINT `pk_nfeProdutos`              PRIMARY KEY (`id`),
    CONSTRAINT `fk_nfeProdutos_nfeDocumentos` FOREIGN KEY (`nfeDocumentoId`) REFERENCES `nfeDocumentos` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
